name = input("What is your name? ")
age = input("what is your age? ")
print("Wow! ", name, "You are ", age, "years old!")
number1 = input("Give me the first number: ")
number2 = input("Give me the second number: ")
answer = float(number1) * float(number2)
print("Here is the answer to multiplying number1 and number2: ",number1, number2, answer)
print("Here is the answer to {} and {} is {}".format(number1, number2, answer))